### ISSUE TITLE
Download fails for larger files (10,000+ rows)

### ISSUE THREAD

**Issue by lagarib** [deblanco/xlsExport#3]
Download fails with 'Network Error' in Chrome 64

**Comment by deblanco** [comment]
Hello,

Thanks for report the issue.
I made some test and that was true - also I found that makes browser unstable with long URL strings - so I changed the exportCSV method to send the data like a Blob.

Find it updated in the new tag **v1.5.1.**

Regards

**Comment by ashutilov** [comment]
Hi, the same issue happens with XlsExport method.
Could you also change it as well to handle Blob?
Thanks in advance.

**Comment by deblanco** [comment]
@ashutilov, I've made the necessary changes to make it works in v1.5.2 version.
I found that it works between 15k-20k row, more than that will show a blank page,  I'll go in deep this week.
